# -*- coding: utf-8 -*-
"""Pixel-CLIP Search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvGgowG_SSmMJBhEtaWKzB4bsbY7pl9s

Install Libaries
"""

!pip install pillow matplotlib

from PIL import Image
import matplotlib.pyplot as plt
import os

"""Upload Input Image"""

from google.colab import files

uploaded = files.upload()

image_path = list(uploaded.keys())[0]

print("Uploaded image:", image_path)

from PIL import Image
import matplotlib.pyplot as plt
import os

print("Libraries loaded successfully!")

image = Image.open(image_path).convert("RGB")

plt.figure(figsize=(6, 6))
plt.imshow(image)
plt.axis("off")
plt.title("Original Input Image")
plt.show()

"""Convert input to Pixel Image"""

# Create a pixelated version of the input image

# Resize to a very small resolution
small_image = image.resize((32, 32), Image.Resampling.NEAREST)

# Resize it back to a larger size
pixel_image = small_image.resize((512, 512), Image.Resampling.NEAREST)

print("Pixel image created successfully!")

plt.figure(figsize=(12, 5))

# Original image
plt.subplot(1, 2, 1)
plt.imshow(image)
plt.axis("off")
plt.title("Original Input")

# Pixel image
plt.subplot(1, 2, 2)
plt.imshow(pixel_image)
plt.axis("off")
plt.title("Pixel Image")

plt.show()

"""Saving Pixel Image"""

pixel_image_path = "pixel_input.png"
pixel_image.save(pixel_image_path)

print("Saved as:", pixel_image_path)

"""Load model"""

model_name = "openai/clip-vit-base-patch32"

import torch
from transformers import CLIPProcessor, CLIPModel

# Use CPU only
device = "cpu"

print("Using device:", device)

# Load pre-trained CLIP model
model_name = "openai/clip-vit-base-patch32"

model = CLIPModel.from_pretrained(model_name)
processor = CLIPProcessor.from_pretrained(model_name)

# Move model to CPU
model = model.to(device)

# Evaluation mode
model.eval()

print("CLIP model loaded successfully!")

print("Total images:", len(image_path))
print("First image:", image_path[0])

"""Using CLIP model for Image"""

# Prepare the pixel image for CLIP

inputs = processor(
    images=pixel_image,
    return_tensors="pt"
)

inputs = {
    key: value.to(device)
    for key, value in inputs.items()
}

# Generate image features
with torch.no_grad():
    output = model.get_image_features(**inputs)

# Get the actual tensor
if hasattr(output, "pooler_output"):
    image_features = output.pooler_output
else:
    image_features = output

# Normalize the embedding
image_features = image_features / image_features.norm(
    p=2,
    dim=-1,
    keepdim=True
)

print("Pixel image embedding created!")
print("Embedding shape:", image_features.shape)

"""Load old pixel-image dataset"""

import zipfile
import os

zip_path = "/content/input1.zip"
extract_path = "/content/input1"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")
print(os.listdir(extract_path))

print(type(image_path))
print(image_path)

import os

print(os.listdir("/content"))

import glob

image_paths = glob.glob(
    "/content/input1/**/*.png",
    recursive=True
)

image_paths += glob.glob(
    "/content/input1/**/*.jpg",
    recursive=True
)

image_paths += glob.glob(
    "/content/input1/**/*.jpeg",
    recursive=True
)

print("Total images found:", len(image_paths))
print("First few images:", image_paths[:5])

"""Generate CLIP embeddings"""

import numpy as np
from PIL import Image
from tqdm import tqdm

old_image_embeddings = []
old_valid_image_paths = []

print("Processing", len(image_paths), "images...")

for image_path in tqdm(image_paths):

    try:
        img = Image.open(image_path).convert("RGB")

        inputs = processor(
            images=img,
            return_tensors="pt"
        )

        inputs = {
            key: value.to(device)
            for key, value in inputs.items()
        }

        with torch.no_grad():
            output = model.get_image_features(**inputs)

        # Handle your Transformers version
        if hasattr(output, "pooler_output"):
            features = output.pooler_output
        else:
            features = output

        # Normalize
        features = features / features.norm(
            p=2,
            dim=-1,
            keepdim=True
        )

        old_image_embeddings.append(
            features.cpu().numpy()[0]
        )

        old_valid_image_paths.append(image_path)

    except Exception as e:
        print("Skipping:", image_path)
        print("Error:", e)

old_image_embeddings = np.array(old_image_embeddings)

print("\nDone!")
print("Embeddings shape:", old_image_embeddings.shape)
print("Valid images:", len(old_valid_image_paths))

"""Enter text query"""

# Enter your search query

query = input("Enter your image search query: ")

print("Your query:", query)

"""CLIP for text query"""

# Prepare text query for CLIP

text_inputs = processor(
    text=[query],
    return_tensors="pt",
    padding=True
)

text_inputs = {
    key: value.to(device)
    for key, value in text_inputs.items()
}

with torch.no_grad():
    text_features = model.get_text_features(**text_inputs)

# Handle Transformers output
if hasattr(text_features, "pooler_output"):
    text_features = text_features.pooler_output

# Normalize
text_features = text_features / text_features.norm(
    p=2,
    dim=-1,
    keepdim=True
)

print("Text embedding created!")
print("Shape:", text_features.shape)

"""Cosine similarity"""

# Calculate similarity between query and all pixel images

text_embedding = text_features.cpu().numpy()[0]

similarities = np.dot(
    old_image_embeddings,
    text_embedding
)

# Get top 5 matching images
top_k = 5

top_indices = np.argsort(similarities)[::-1][:top_k]

print("Top matching images:\n")

for rank, index in enumerate(top_indices, start=1):
    print(
        rank,
        old_valid_image_paths[index],
        "Similarity:",
        round(float(similarities[index]), 4)
    )

"""Display input image"""

# Display the original uploaded input image separately

plt.figure(figsize=(6, 6))

plt.imshow(image)
plt.axis("off")
plt.title("Original Input Image", fontsize=16)

plt.show()

"""Display
  - Pixel input
   - Matching pixel images
"""

import matplotlib.pyplot as plt
from PIL import Image

# Number of dataset results to display
top_k = 5

# Create figure
plt.figure(figsize=(18, 5))

plt.subplot(1, top_k + 1, 1)

plt.imshow(pixel_image)
plt.axis("off")
plt.title("Your Input\n(Pixel)")

for rank, index in enumerate(top_indices, start=2):

    img_path = old_valid_image_paths[index]

    img = Image.open(img_path).convert("RGB")

    plt.subplot(1, top_k + 1, rank)
    plt.imshow(img)
    plt.axis("off")

    similarity = similarities[index]

    plt.title(
        f"Match {rank-1}\n{similarity:.2f}"
    )

plt.suptitle(
    f'Query: "{query}"',
    fontsize=16
)

plt.tight_layout()
plt.show()